export {
  DEFAULT_ISSUER,
  FEDERATION_ENDPOINT,
  SESSION_DURATION_SECONDS,
  buildLoginUrl,
  createOidcGateway,
  createSsoGateway,
  defaultDestination,
  federateToConsole,
  getRoleCredentials,
  getSigninToken,
  listAccountsWithRoles,
  pollForToken,
  refreshAccessToken,
  registerClient,
  startDeviceAuthorization,
  type AccountWithRoles,
  type DeviceAuthorization,
  type RegisteredClient,
  type RoleCredentials,
  type SsoToken,
} from "../src/main/FederationService.ts";
